name:                vass
version:             0.1.0.0
github:              "dixonary/vass"
license:             BSD3
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2019 Alex Dixon"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Haskell implementation of Vector Addition Systems with States.
# category:            data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: >
  Please see <Data-VASS.html Data.VASS> for more details 
  about the data structure.

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- megaparsec
- filepath
- mtl
- diagrams
- diagrams-svg
- diagrams-core 
- diagrams-lib
- diagrams-contrib
- SVGFonts
- pretty-simple

default-extensions:
- TypeSynonymInstances
- UnicodeSyntax
- RecordWildCards
- OverloadedStrings
- QuasiQuotes
- LambdaCase
- FlexibleInstances
- TupleSections
- LambdaCase
- GeneralizedNewtypeDeriving
- TypeFamilies

library:
  source-dirs: src