name:                vass
version:             0.1.0.0
github:              "dixonary/vass"
license:             BSD3
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2019 Alex Dixon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dixonary/vass#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src